### PR TITLE
add plugin build

### PR DESCRIPTION
**Pull request by coolya**
Create a basic build solution to produce a plugin you could publish on the marketplace. This stuff can be a little tricky because the MPS languages for it are janky af. 

I had to add a workaround to the constrained datatype for "Byte".  (see the 4f89e8b commit msg for more details)

### CODE REVIEW

**Comment by iconmaster5326** [comment]
I'm thinking the double-backslash thing isn't a bug, because it allows you to provide both char constants like `\n` and char classes like `\\s`. But it sure is annoying. Good catch there!

**Comment by iconmaster5326** [comment]
Maybe I should have uploaded the plugin before merging, because when I try, I get this error:

image

Any suggested fix?

**Comment by iconmaster5326** [comment]
It looks like all I need to do is add an XML tag to the build.xml like this one:

```xml
<idea-version since-build="X" until-build="X.*" />
```

But what version to put where `X` is? `version`? `build.number`? `idea.platform.build.number`?

**Comment by coolya** [comment]
yes and the vendor info on the plugin like your name.

**Comment by iconmaster5326** [comment]
Already filled in the vendor info.

**Comment by iconmaster5326** [comment]
There we go. Plugin published! Thanks again, @coolya! https://plugins.jetbrains.com/plugin/16483-binarygen

**Pull request merged**
